GRANT ALL PRIVILEGES on spam_ml.* to 'postgres_user';
CREATE SCHEMA IF NOT EXISTS spam_ml DEFAULT CHARACTER SET utf8;


CREATE TABLE IF NOT EXISTS spam_ml.User (
  id INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  username VARCHAR(200) NOT NULL UNIQUE,
  document_number VARCHAR(14) NOT NULL UNIQUE,
  phone VARCHAR(120) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY id (id),
  UNIQUE KEY UC_person_key (user_key),
  UNIQUE KEY UC_email (email),
);