version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn app.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      FIRST_SUPERUSER_EMAIL: "teste@yopmail.com"
      WORKERS_PER_CORE: "1"
      MAX_WORKERS: "1"
      LOCAL_PORT: ${LOCAL_PORT}
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: database.Dockerfile
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
#     expose:
#       - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=spam_ml
#     ports:
#       - "0.0.0.0:5432:5432"
    ports:
      - 5432

volumes:
  postgresql_data: