version: '3.7'

services:
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - local.env
    depends_on:
      - db

  db:
    build: database.Dockerfile
   volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=example
      - name=value
      - POSTGRES_DB=spam_ml
    ports:
      - "5432:5432"

volumes:
  postgresql_data: