"""test migr

Revision ID: 1bc12ec23e23
Revises: 5568cdd1a544
Create Date: 2022-03-30 17:50:08.405924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc12ec23e23'
down_revision = '5568cdd1a544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
